### ISSUE TITLE
Re-vamp Lobby Form

### ISSUE THREAD

**Issue by HowiJ** [TeamDicey/dice-frontend#2]
# Components
- LobbyForm.tsx

# Blockers
Blocked by [Button and Input Components](https://github.com/HowiJ/dice-frontend/issues/3)

# Description
The goal here is to change the Styling on the Lobby Form. @HowiJ will create a button and input components to use for this. Currently, make the "Join Lobby" a TextInput for now and the click of the arrow next to it a button to join. We will change this later in the next task
See pictures below

## What it should end up looking like
![Image](https://user-images.githubusercontent.com/17022825/200790172-b5fcbfd0-bd5e-4250-ad9d-dcdc50aacaa0.png)

## Input
![Image](https://user-images.githubusercontent.com/17022825/200790350-340be2de-61cc-4cc1-abfe-fce1c2fd755f.png)

**Comment by JonWong37** [comment]
First screenshot is how the lobby currently looks.
Implemented the Button component into LobbyForm

Second screenshot shows hovering over the button high-lighting the first button.
Third screenshot shows hovering over the button and high-lighting the 2nd button.


<img width="1440" alt="Screen Shot 2022-12-01 at 7 30 15 PM" src="https://user-images.githubusercontent.com/110418682/205209848-996844a0-15ff-43ed-9108-5c433e0d3c56.png">

Second screenshot shows hovering over the button high-lighting the first button.
Third screenshot shows hovering over the button and high-lighting the 2nd button.
Added the hovering colors to the buttons. I set them up as 2 separate Css for each button.

<img width="1440" alt="Screen Shot 2022-12-01 at 7 30 33 PM" src="https://user-images.githubusercontent.com/110418682/205209924-a167a362-40c5-4485-88d1-a213cb54fbb5.png">
<img width="1440" alt="Screen Shot 2022-12-01 at 7 30 41 PM" src="https://user-images.githubusercontent.com/110418682/205209937-edc84f31-98d0-48d8-a5c3-f09fee6c443a.png">

Fourth shows onClick active for the button to change colors and shows responsiveness to when being clicked.

<img width="1440" alt="Screen Shot 2022-12-01 at 7 31 24 PM" src="https://user-images.githubusercontent.com/110418682/205209947-4616df25-a52f-41f9-b061-f8102d4af49a.png">

Fifth screenshot shows displays inputing target into the "Join lobby"

<img width="1440" alt="Screen Shot 2022-12-01 at 7 44 09 PM" src="https://user-images.githubusercontent.com/110418682/205210242-d6302c49-4797-4124-bfa0-de1e023dc3b5.png">

Potential Issues : The spacing for the button components for "Create Lobby" and "Join Lobby" are uneven. They're not perfectly aligned. I was manually setting the width of these components. There is definitely a better way to do it. 

The highlight within the button is done with setting the padding to 0 to get rid of div spacing issue that I previously mentioned. Please let me know on your feedback regarding this issue.

**Comment by JonWong37** [comment]
Branches for the PR for this issue has been merged and deleted. Closing the issue
